CREATE TABLE `login_otp_challenge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `challenge_id` VARCHAR(64) NOT NULL,
  `username` VARCHAR(120) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `app_user_id` INT NOT NULL,
  `otp_hash` VARCHAR(255) NULL,
  `otp_expires_at` DATETIME(0) NOT NULL,
  `attempt_count` INT NOT NULL DEFAULT 0,
  `max_attempts` INT NOT NULL DEFAULT 3,
  `resend_count` INT NOT NULL DEFAULT 0,
  `resend_available_at` DATETIME(0) NOT NULL,
  `last_sent_at` DATETIME(0) NOT NULL,
  `challenge_status` ENUM('PENDING', 'VERIFIED', 'FAILED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
  `token_bundle_ciphertext` TEXT NULL,
  `consumed_at` DATETIME(0) NULL,
  `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `updated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  UNIQUE INDEX `uniq_login_otp_challenge_challenge_id`(`challenge_id`),
  INDEX `idx_login_otp_challenge_username_status`(`username`, `challenge_status`),
  INDEX `idx_login_otp_challenge_otp_expires_at`(`otp_expires_at`),
  INDEX `idx_login_otp_challenge_status_resend`(`challenge_status`, `resend_available_at`),
  INDEX `idx_login_otp_challenge_app_user_id`(`app_user_id`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
